### ISSUE TITLE
Can't build driver above v4.0.5

### ISSUE THREAD

**Issue by Vkutovoy92** [silviucpp/erlcass#61] opened 2024-01-11 09:46 UTC
Hi, I have 24.3.4 erlang and I have tried to build drivers.

4.0.4 - OK
4.0.5 - OK
4.0.6 - ERROR

```
 LD     erlcass_nif.so

Undefined symbols for architecture x86_64:
  "_ERR_new", referenced from:
      datastax::internal::core::OpenSslContext::set_cert(char const*, unsigned long) in libcassandra_static.a(ssl_openssl_impl.cpp.o)
  "_ERR_set_debug", referenced from:
      datastax::internal::core::OpenSslContext::set_cert(char const*, unsigned long) in libcassandra_static.a(ssl_openssl_impl.cpp.o)
  "_ERR_set_error", referenced from:
      datastax::internal::core::OpenSslContext::set_cert(char const*, unsigned long) in libcassandra_static.a(ssl_openssl_impl.cpp.o)
  "_SSL_get1_peer_certificate", referenced from:
      datastax::internal::core::OpenSslSession::verify() in libcassandra_static.a(ssl_openssl_impl.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [nif.mk:78: /Users/vitalijkutovoj/Documents/counters/_build/default/lib/erlcass/priv/erlcass_nif.so] Error 1
make[2]: Leaving directory '/Users/vitalijkutovoj/Documents/counters/_build/default/lib/erlcass/c_src'
make[1]: *** [Makefile:44: nif_compile] Error 2
make[1]: Leaving directory '/Users/vitalijkutovoj/Documents/counters/_build/default/lib/erlcass'
===> Hook for compile failed!
```

Something with SSL if I have understood correct, can you recommend what should I do?
MacOS - 12.5.1 (21G83)
~openssl version
OpenSSL 3.2.0 23 Nov 2023 (Library: OpenSSL 3.2.0 23 Nov 2023)

~brew --prefix openssl@1.1
/usr/local/opt/openssl@1.1

**Comment by Vkutovoy92** [comment] 2024-01-11 10:13
I have tried to use c_src/Makefile from 4.0.5 to 4.0.6 and OK, build is successful. How to fix it global?

**Comment by silviucpp** [comment] 2024-01-11 10:18
Please try last version. is not working ? Datastax moved to openssl 3 not using any longer 1.x.

Provide also the output of `brew --prefix openssl` .It might be a problem with your openssl installs.

**Comment by silviucpp** [comment] 2024-01-11 10:21
In fact I see the problem is fixed on master not on last release. 

can you please confirm ?

Silviu

**Comment by Vkutovoy92** [comment] 2024-01-11 10:25
> Please try last version. is not working ? Datastax moved to openssl 3 not using any longer 1.x.
> 
> Provide also the output of `brew --prefix openssl` .It might be a problem with your openssl installs.

1. DN010992KVO1:include vitalijkutovoj$ brew --prefix openssl
/usr/local/opt/openssl@3

2. v4.1.0 the same
 ```
LD     erlcass_nif.so
Undefined symbols for architecture x86_64:
  "_ERR_get_error_all", referenced from:
      datastax::internal::core::OpenSslSession::check_error(int) in libcassandra_static.a(ssl_openssl_impl.cpp.o)
      ssl_log_errors(char const*) in libcassandra_static.a(ssl_openssl_impl.cpp.o)
  "_ERR_new", referenced from:
      datastax::internal::core::OpenSslContext::set_cert(char const*, unsigned long) in libcassandra_static.a(ssl_openssl_impl.cpp.o)
  "_ERR_set_debug", referenced from:
      datastax::internal::core::OpenSslContext::set_cert(char const*, unsigned long) in libcassandra_static.a(ssl_openssl_impl.cpp.o)
  "_ERR_set_error", referenced from:
      datastax::internal::core::OpenSslContext::set_cert(char const*, unsigned long) in libcassandra_static.a(ssl_openssl_impl.cpp.o)
  "_SSL_get1_peer_certificate", referenced from:
      datastax::internal::core::OpenSslSession::verify() in libcassandra_static.a(ssl_openssl_impl.cpp.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by Vkutovoy92** [comment] 2024-01-11 10:32
> In fact I see the problem is fixed on master not on last release.
> 
> can you please confirm ?
> 
> Silviu

Last master build is OK!

**Comment by Vkutovoy92** [comment] 2024-01-11 10:34
Do you have a plan to release new version with this fix?

**Comment by Vkutovoy92** [comment] 2024-01-11 10:49
I changed in 4 1 0
OPENSSL_ROOT := $(shell brew --prefix openssl) instead of 
OPENSSL_ROOT := $(shell brew --prefix openssl@1.1)
And it works!

**Comment by silviucpp** [comment] 2024-01-11 19:11
Master it's working for you ? without any change please.

**Comment by Vkutovoy92** [comment] 2024-01-11 19:15
> Master it's working for you ? without any change please.

Yea, of course! And  all versions  above 4.0.5 work with makefile from master branch.

**Comment by Vkutovoy92** [comment] 2024-01-11 19:20
I checked with my mac and alpine 3.17 and ubuntu. No problems!

**Comment by silviucpp** [comment] 2024-01-11 21:09
I released a new version with the master code.

**Closed by silviucpp** 2024-01-11 21:09 UTC
